source "https://rubygems.org"

gem 'activerecord', '6.1.7.1', :require => 'active_record'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'tux'
gem 'httparty'
gem 'bcrypt'
gem 'pry'
gem 'rack-flash3'
gem 'sysrandom'
gem 'pg'